// MOST OF THE CODE IS SYNCHRONOUS, MEANING LINE BY LINE CODE EXECUTION
// ITS FINE UNTILL THE EXECUTION TAKES NOT MORE TIME TO COMPLETE
// AN alert() IS AN EXAMPLE OF BLOKING CODE, UNTILL USER CLICKS OK IT BLOCKS THE EXECUTION
// 

// ASYNCHRONOUS CODE IS NON BLOCKING CODE
// SETIMEOUT IS AN EXAMPLE OF ASYNCHRONOUS CODE
// CALL BACK FUNCTION DOESNT JUST MAKE ASYNCHRONOUS CODE, FOR EXAMPLE ARRAY.MAP()

